### ISSUE TITLE
Create a stable build for v.0.1.0 release!

### ISSUE THREAD

**Issue by Erlendos12** [EBSP-Indexer/EBSP-Indexer#118]
Fix issues discovered during usability test and other minor improvements.

**Comment by hakonanes** [comment]
Sounds good, thanks for letting me know your plans (:

**Comment by Erlendos12** [comment]
@all-contributors
please add @htrellin for code, bug, doc, ideas.
please add @olavlet for code, bug, doc, ideas.
please add @Erlendos12 for code, bug, doc, ideas.

**Comment by Erlendos12** [comment]
Date for release has been delayed to 12. Friday.
