### ISSUE TITLE
Refinement fails when crystal map contains not_indexed datapoints

### ISSUE THREAD

**Issue by htrellin** [EBSP-Indexer/EBSP-Indexer#140]
Refinement of crystal maps containing data points that are labeled "not_indexed" will fail due to a known bug in the merge method in Kikuchipy 0.8.4, bug will probably be resolved when Kikuchipy 0.8.5 is released.

**Comment by hakonanes** [comment]
A fix for this issue was just released in kikuchipy v0.8.5.
